[build]
builder = "docker"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ASYNC_SQLALCHEMY = "true"
HUGGINGFACEHUB_API_TOKEN = "YOUR_HUGGINGFACE_TOKEN_HERE"

[volume]
name = "data"
mountPath = "/data"

